language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
install: pip install --upgrade --requirement dev-requirements.txt
script:
  - isort --quiet --diff --recursive
  - isort --check-only --recursive
  - flake8
  - python setup.py check
  - check-manifest
